apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      name: {{ template "fullname" . }}
    spec:
      serviceAccount: {{ .Release.Name }}-sa
      hostPID: true
      containers:
      - name: {{ template "fullname" . }}
        image: "{{.Values.global.imageCredentials.registry}}/enforcer:{{.Values.global.imageTag}}"
        imagePullPolicy: {{.Values.global.imagePullPolicy}}
        securityContext:
          privileged: true
        env:
          - name: "AQUA_TOKEN"
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-enforcer-token
                key: token
          - name: AQUA_SERVER
            value: {{ .Release.Name }}-aqua-gateway
          - name: AQUA_LOGICAL_NAME
            value: {{ .Release.Name }}-eks
          - name: RESTART_CONTAINERS
            value: "no"
          - Name: "AQUA_RUN_WATCHER"
            Value: "yes"
        volumeMounts:
          - mountPath: /var/run
            name: var-run
          - mountPath: /dev
            name: dev
          - mountPath: /host/sys
            name: sys
            readOnly: true
          - mountPath: /host/proc
            name: proc
            readOnly: true
          - mountPath: /host/etc
            name: etc
            readOnly: true
          - mountPath: /host/opt/aquasec
            name: aquasec
            readOnly: true
          - mountPath: /opt/aquasec/tmp
            name: aquasec-tmp
          - mountPath: /opt/aquasec/audit
            name: aquasec-audit
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
        - name: etc
          hostPath:
            path: /etc
        - name: aquasec
          hostPath:
            path: /opt/aquasec
        - name: aquasec-tmp
          hostPath:
            path: /opt/aquasec/tmp
        - name: aquasec-audit
          hostPath:
            path: /opt/aquasec/audit

