{{ if .Values.global.dbExternalServiceHost }}
{{ else }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      name: {{ template "fullname" . }}
    spec:
      serviceAccount: {{ .Release.Name }}-sa
      containers:
      - name: {{ template "fullname" . }}
        image: "{{.Values.global.imageCredentials.registry}}/marketplace-database:{{.Values.global.imageTag}}"
        imagePullPolicy: {{.Values.global.imagePullPolicy}}
        env:
          - name: PGDATA
            value: "/var/lib/postgresql/data/db-files"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.Release.Name}}-database-password
                key: password
        ports:
        - containerPort: {{.Values.database.containerPort}}
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: "{{ .Release.Name }}-database-vol"
      volumes:
        - name: "{{ .Release.Name }}-database-vol"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-database-pvc"
{{ end }}
